/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectresto;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Witjaksono
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setTanggal();
        tfNama.setText(""+username);
    }
    

    public String username;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbMenu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        bPrint = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bDelete1 = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        tfTumbal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbTanggal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel1.setText("Nama Menu");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 200, 31);

        cbMenu.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        cbMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indomie Rebus", "Telur Ceplok", "Es Teh", "Kopi" }));
        jPanel2.add(cbMenu);
        cbMenu.setBounds(20, 40, 198, 31);

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel2.setText("Jumlah");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 80, 200, 31);
        jPanel2.add(tfJumlah);
        tfJumlah.setBounds(20, 110, 200, 29);

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setText("Harga");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 150, 200, 31);
        jPanel2.add(tfHarga);
        tfHarga.setBounds(20, 180, 200, 29);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        tbData.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Kasir", "Menu", "Jumlah", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 570, 370);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(240, 10, 590, 390);

        bPrint.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bPrint.setText("PRINT");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        jPanel2.add(bPrint);
        bPrint.setBounds(20, 340, 200, 30);

        bSave.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bSave.setText("SAVE");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel2.add(bSave);
        bSave.setBounds(20, 250, 200, 30);

        bClear.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bClear.setText("CLEAR");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel2.add(bClear);
        bClear.setBounds(20, 310, 200, 30);

        bDelete1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bDelete1.setText("DELETE");
        bDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelete1ActionPerformed(evt);
            }
        });
        jPanel2.add(bDelete1);
        bDelete1.setBounds(20, 280, 200, 30);

        bRefresh.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bRefresh.setText("REFRESH");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(bRefresh);
        bRefresh.setBounds(20, 370, 200, 30);
        jPanel2.add(tfTumbal);
        tfTumbal.setBounds(0, 0, 0, 0);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 840, 420);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        lbTanggal.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lbTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbTanggal);
        lbTanggal.setBounds(70, 50, 120, 31);

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selamat Datang");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 10, 120, 31);

        tfNama.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        tfNama.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(tfNama);
        tfNama.setBounds(140, 10, 120, 31);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(579, 0, 260, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 100);

        setSize(new java.awt.Dimension(856, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        int jml = Integer.parseInt(tfJumlah.getText().toString());
        if("".equals(tfJumlah.getText()) || "".equals(tfHarga.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String MN = "";
            if(cbMenu.getSelectedItem().equals("Indomie Rebus"))
            {
                MN = "1";
            }
            if(cbMenu.getSelectedItem().equals("Telor Ceplok"))
            {
                MN = "2";
            }
            if(cbMenu.getSelectedItem().equals("Es Teh"))
            {
                MN = "3";
            }
            if(cbMenu.getSelectedItem().equals("Kopi"))
            {
                MN = "4";
            }           
          String SQL = "INSERT INTO tb_transaksi (tanggal_transaksi,menu,jumlah,harga)"+"VALUES('"+lbTanggal.getText()+"','"+MN+"','"+tfJumlah.getText()+"','"+tfHarga.getText()+"')";
          int status = KoneksiDB.execute(SQL);
          if(status == 1){
              JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
              selectData();
          } else {
              JOptionPane.showMessageDialog(this,"Data GAGAL ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
          }
        }
        
    }//GEN-LAST:event_bSaveActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelete1ActionPerformed
        // TODO add your handling code here:
        int baris = tbData.getSelectedRow();
        if(baris != -1)
        {
            String NIS = tbData.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE id_transaksi='"+tfTumbal.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1)
            {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "GAGAL", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Yang Akan Di Hapus", "ERROR", JOptionPane.WARNING_MESSAGE);
        }

    
    }//GEN-LAST:event_bDelete1ActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        // TODO add your handling code here:
        int baris = tbData.getSelectedRow();
        if(baris != -1)
        {
            tfTumbal.setText(tbData.getValueAt(baris, 0).toString());
        }
    }//GEN-LAST:event_tbDataMouseClicked

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        tfJumlah.setText("");
        tfHarga.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        // TODO add your handling code here:
         MessageFormat header = new MessageFormat("Warung Sandhy Putra");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)");
        try
        {
            tbData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannont Print%s%n", e.getMessage());
        }
        
    }//GEN-LAST:event_bPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete1;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<String> cbMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JLabel tfNama;
    private javax.swing.JTextField tfTumbal;
    // End of variables declaration//GEN-END:variables
    public void selectData() 
    {
        String kolom[] = {"ID_Transaksi","Tanggal","Menu","Jumlah","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try
        {
            while(rs.next())
            {
                String ID_Transaksi = rs.getString(1);
                String Tanggal = rs.getString(2);
                String Menu = "";
                   if("1".equals(rs.getString(3)))
                   {
                       Menu = "Indomie Rebus";
                   }
                   if("2".equals(rs.getString(3)))
                   {
                       Menu = "Telur Ceplok";
                   }
                   if("3".equals(rs.getString(3)))
                   {
                       Menu = "Es Teh";
                   }
                   if("4".equals(rs.getString(3)))
                   {
                       Menu = "Kopi";
                   }                   
                String Jumlah = rs.getString(4);
                String Harga = rs.getString(5);
                String data[] = {ID_Transaksi,Tanggal,Menu,Jumlah,Harga};
                dtm.addRow(data);
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbData.setModel(dtm);
    }
    public void setTanggal()
    {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        lbTanggal.setText(kal.format(skrg));
    }
}

